import type { Puzzle, QuizData } from "../schema/quiz.ts";

export type { Puzzle, QuizData };

/** Highest threshold first; the first entry whose `min` is met wins. */
export interface RankThreshold {
  min: number;
  rank: string;
}

export interface EngineConfig {
  wrongPenalty: number;
  rankMode: "absolute" | "percent";
  roomLabel: string; // e.g. "Room" vs "Zone"
  absoluteRanks: RankThreshold[];
  percentRanks: RankThreshold[];
}

/**
 * Which top-level screen is showing. The vanilla engine tracked this implicitly
 * by toggling `display` on `.screen` elements; as a real state field it is one
 * source of truth and the router can key off it.
 */
export type Phase = "title" | "playing" | "final" | "victory";

/**
 * An answer in progress. Each puzzle type owns its own shape:
 * mcq a single key, multiselect a key set, order the current sequence of item
 * ids, match a left-id to right-id mapping.
 */
export type PuzzleAnswer = string | null | string[] | Record<string, string>;

export interface PuzzleResult {
  correct: boolean;
  /** Points awarded; only meaningful when `correct`. */
  points: number;
  explanation?: string;
  penalty: number;
  /**
   * Seconds between the puzzle first becoming active and being solved correctly.
   * Only set once, on the submission that solves it.
   */
  timeSpent?: number;
  /**
   * Increments on every submission of this puzzle. Effects that fire per attempt
   * -- the sound, the shake animation -- key off this, because two consecutive
   * wrong answers otherwise produce an identical result object and nothing reruns.
   */
  seq: number;
}

/**
 * Set when a correct answer should hand over to the next puzzle (or the room's
 * code entry) after a beat. The timer lives in an effect rather than a bare
 * setTimeout so unmounting mid-delay cancels it instead of dispatching into a
 * dead reducer.
 */
export interface PendingAdvance {
  roomNum: number;
  nextPuzzleId: number | null;
  delayMs: number;
  /** Distinguishes consecutive advances that otherwise compare equal. */
  seq: number;
}

export interface GameState {
  phase: Phase;
  currentRoom: number;
  score: number;
  puzzlesCompleted: number;
  hintsUsed: number;
  maxHints: number;
  soundEnabled: boolean;
  timeElapsed: number;
  activePuzzles: Record<string, number>;
  codes: Record<string, boolean>;
  roomCompleted: Record<string, boolean>;
  puzzleSolved: Record<string, boolean>;
  puzzleAttempts: Record<string, number>;
  /** `timeElapsed` at the moment each puzzle first became active, for per-puzzle timing. */
  puzzleStartedAt: Record<string, number>;

  // --- Session-only state, never persisted ---
  /** In-progress answers, keyed by puzzle id. */
  answers: Record<string, PuzzleAnswer>;
  /** Display order for shuffled option/item lists, fixed once per session. */
  displayOrder: Record<string, string[]>;
  /** Result banner under each puzzle. */
  results: Record<string, PuzzleResult | undefined>;
  /**
   * Hint revealed per room, if any. The ordinal is captured at reveal time so a
   * hint taken later in another room does not retroactively relabel this one.
   */
  hints: Record<string, { text: string; ordinal: number }>;
  pendingAdvance: PendingAdvance | null;
  /** Screen-reader announcement; `seq` forces a re-announce of identical text. */
  announcement: { text: string; seq: number };
}

/**
 * Exactly the fields the vanilla engine wrote to
 * `escape-room:${quizId}:state`. Keeping the set identical means saves made by
 * the previous build still resume.
 */
export const PERSISTED_KEYS = [
  "currentRoom",
  "score",
  "puzzlesCompleted",
  "hintsUsed",
  "maxHints",
  "soundEnabled",
  "timeElapsed",
  "activePuzzles",
  "codes",
  "roomCompleted",
  "puzzleSolved",
  "puzzleAttempts",
  "puzzleStartedAt",
] as const;

export type PersistedState = Pick<GameState, (typeof PERSISTED_KEYS)[number]>;

export interface BestScore {
  score?: number;
  time?: string;
}

/** One entry of `public/quizzes/index.json`, generated by tools/gen-manifest.ts. */
export interface QuizManifestItem {
  id: string;
  pageTitle: string;
  titleLogo: string;
  titleSub: string;
  version?: string;
  path: string;
}
