/**
 * Vendors the web fonts into public/fonts/ so the game needs no network at all.
 *
 * Why this exists: loading fonts from Google meant the offline single-file
 * bundles fell back to system fonts on a machine with no network, and the CSP
 * had to allow fonts.googleapis.com and fonts.gstatic.com. Self-hosting removes
 * both problems.
 *
 * Run manually (needs network) only when the font list changes:
 *   pnpm fetch-fonts
 *
 * The generated files are committed; the normal build never calls this.
 */
import fs from "node:fs";
import path from "node:path";

/*
 * Jost is the only vendored family: it supplies `--font-display` (titles and
 * headings). Body copy and tabular data use the platform sans and mono stacks,
 * which need no download and render natively.
 *
 * Orbitron and Share Tech Mono used to be vendored here too. They were dropped
 * with the design-system rewrite -- they are the stock "sci-fi terminal" pairing
 * and were most of why the old UI read as generic.
 */
const GOOGLE_CSS = "https://fonts.googleapis.com/css2?family=Jost:wght@400;600;700&display=swap";

// Pretend to be a modern browser or Google serves legacy ttf instead of woff2.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// The quizzes are English with occasional scientific symbols; the other subsets
// (cyrillic, greek, vietnamese) would triple the payload for nothing.
const KEEP_SUBSETS = ["latin", "latin-ext"];

const outDir = path.resolve("public/fonts");

async function main() {
  const cssResp = await fetch(GOOGLE_CSS, { headers: { "User-Agent": UA } });
  if (!cssResp.ok) throw new Error(`Failed to fetch font CSS: ${cssResp.status}`);
  const css = await cssResp.text();

  fs.mkdirSync(outDir, { recursive: true });

  // Google emits a `/* subset */` comment before each @font-face block.
  const blocks = css.split(/\/\*\s*/).filter((b) => b.includes("@font-face"));
  const kept: string[] = [];
  let downloaded = 0;

  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf("*/")).trim();
    if (!KEEP_SUBSETS.includes(subset)) continue;

    const face = block.slice(block.indexOf("@font-face"));
    const urlMatch = face.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/);
    if (!urlMatch) continue;

    const remote = urlMatch[1];
    const family = (face.match(/font-family:\s*'([^']+)'/) ?? [])[1] ?? "font";
    const weight = (face.match(/font-weight:\s*(\d+)/) ?? [])[1] ?? "400";
    const filename = `${family.replace(/\s+/g, "-").toLowerCase()}-${weight}-${subset}.woff2`;

    const fontResp = await fetch(remote, { headers: { "User-Agent": UA } });
    if (!fontResp.ok) throw new Error(`Failed to fetch ${remote}: ${fontResp.status}`);
    fs.writeFileSync(path.join(outDir, filename), Buffer.from(await fontResp.arrayBuffer()));
    downloaded++;

    kept.push(face.replace(remote, `./${filename}`).trim());
  }

  const header =
    "/* Generated by tools/fetch-fonts.ts -- do not edit by hand.\n" +
    "   Fonts are SIL Open Font License 1.1. Re-run `pnpm fetch-fonts` to refresh. */\n\n";
  fs.writeFileSync(path.join(outDir, "fonts.css"), header + kept.join("\n\n") + "\n");

  console.log(`✅ Vendored ${downloaded} font files + fonts.css into ${outDir}`);
}

main().catch((err) => {
  console.error("❌", err.message);
  process.exit(1);
});
